models.py
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy import create_engine, Column, String
from config import Config

Base = declarative_base()

# URL from .env file
engine = create_engine(Config.SQLALCHEMY_DATABASE_URI)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Models inline with Database
class User(Base):
    __tablename__ = 'fact_UserIBC'
    email = Column(String, primary_key=True, index=True)
    password = Column(String)
    name = Column(String)

def get_db():
    db = SessionLocal()

    try:
        yield db
    
    finally:
        db.close()

app.py
from flask import Flask, render_template
from datetime import datetime
from routes.arrival_check import arrival_check_app
from routes.storage_maintenance_list import storage_maintenance_list_app
from routes.pre_delivery_list import pre_delivery_app
from routes.ibc import ibc_app
from routes.storage_maintenance_list import storage_maintenance_list_app
from routes.auth import auth_bp

app = Flask(__name__)
app.secret_key = 'secret-key'

# register semua blueprint
app.register_blueprint(arrival_check_app)
app.register_blueprint(storage_maintenance_list_app)
app.register_blueprint(pre_delivery_app)
app.register_blueprint(ibc_app)
app.register_blueprint(auth_bp)

@app.route('/')
def base():
    return render_template("Login.html", year=datetime.now().year)

if __name__ == '__main__':
    app.run(debug=True)

routes/arrival_check.py
from flask import Blueprint, render_template
from datetime import datetime

arrival_check_app = Blueprint('arrival_check', __name__)

@arrival_check_app.route('/arrival_check')
def arrival_check():    
    return render_template("Arrival_check.html", year=datetime.now().year)

routes/auth.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
from werkzeug.security import check_password_hash
from models import db, User
from Service.service import emailService
import random
import string

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

# class for Login & OTP
class authController:
    def __init__(self):
        self.email_service = emailService()

    def generate_OTP(self, length=6):
        return ''.join(random.choices(string.digits, k=length))
    
    def verify_credentials(self, email, password):
        user = User.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            return user
        return None
    
    def send_otp(self, to_email, otp_code):
        subject = "Your OTP Code"
        body = f"Hi, Here is your OTP code: {otp_code}"
        self.email_service.send_email(to_email, subject, body)

auth_controller = authController()

# Route: Login
@auth_bp.route('/login', methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = auth_controller.verify_credentials(email, password)

        if user:
            otp_code = auth_controller.generate_OTP()
            session['otp'] = otp_code
            session['email'] = user.email
            session['name'] = user.name
            auth_controller.send_otp(user.email, otp_code)

            flash("OTP have sent to your Email", "info")
            return redirect(url_for("auth.verify_otp"))
        
        else:
            flash("Invalid Email and Password", "danger")
    
    return render_template('login.html', hide_nav=True)

# Route: verify OTP
@auth_bp.route('/verify_otp', methods=["GET","POST"])
def verify_OTP():
    if request.method == "POST":
        entered_OTP = request.form.get('otp')

        if entered_OTP == session.get('otp'):
            session["username"] == session.get('name')
            flash("Login Successful", "success")
            return redirect(url_for("arrival_check.arrival_check"))
        else:
            flash("OTP is Incorrect", "danger")

    return render_template("Verify_OTP.html", hide_nav=True)

@auth_bp.route('/logout')
def logout():
    
    session.clear()
    return redirect(url_for('auth.login'))

routes/ibc.py
from flask import Blueprint, render_template
from datetime import datetime

ibc_app = Blueprint('IBC', __name__)

@ibc_app.route('/IBC')
def ibc_form():    
    return render_template("IBC.html", year=datetime.now().year)

routes/pre_delivery_list.py
from flask import Blueprint, render_template
from datetime import datetime

pre_delivery_app = Blueprint('pre_delivery_list', __name__)

@pre_delivery_app.route('/pre_delivery_list')
def pre_delivery_list():    
    return render_template("Pre_delivery_list.html", year=datetime.now().year)

routes/storage_maintenance_list.py
from flask import Blueprint, render_template
from datetime import datetime

storage_maintenance_list_app = Blueprint('storage_maintenance_bp', __name__)

@storage_maintenance_list_app.route('/storage_maintenance_list')
def storage_maintenance_list():    
    return render_template("Storage_maintenance_list.html", year=datetime.now().year)

templates/Arrival_check.html
<!-- templates/arrival_check.html -->
{% extends 'Base.html' %}
{% block content %}
    <h2>Arrival Check Form (Comming Soon)</h2>
{% endblock %}

templates/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Indotraktor Interdepartment Business Case{% endblock %}</title>

    <!-- < external CSS > -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <!-- Bootstrap Icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
</head>
<body>
    {% if not hide_nav %}
    <div class="header-wrapper">
        <header class="text-white py-3 px-4 d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
                <!-- toggle button -->
                <button class="border-0 bg-transparent me-3" id="sideBarToogle"><i class="bi bi-list fs-3 text-white"></i></button>
                <h1 class="h4 m-0"> Indotraktor Interdepartment Business Case </h1>    
            </div>
            {% if session.get('username') %}
            <div class="ms-auto d-flex align-items-center">
                <span class="me-3"> Hi, {{ session.username }} </span>
                <a href="{{ url_for('auth.logout') }}" class="btn btn-light btn-sm"> Log Out </a>
            </div>
            {% endif %}
        </header>
    </div>
    {% endif %}
    <div class="navbar-menu">
        <!-- sidebar navigation -->
        {% if not hide_nav %}
        <nav class="sidebar" id="sidebar">
            <h3 class="mb-3"> Menu </h3>
            <a href="{{ url_for('arrival_check.arrival_check') }}"><i class="bi bi-plus-circle me-3"></i> Arrival Check Form </a>
            <a href="{{ url_for('storage_maintenance_bp.storage_maintenance_list') }}"><i class="bi bi-plus-circle me-3"></i> Storage Maintenance List Form </a>
            <a href="{{ url_for('pre_delivery_list.pre_delivery_list') }}"><i class="bi bi-plus-circle me-3"></i> Pre Delivery Check List Form </a>
            <a href="{{ url_for('IBC.ibc_form') }}"><i class="bi bi-plus-circle me-3"></i> IBC Form </a>
            <a href="{{ url_for('auth.logout') }}"><i class="bi bi-box-arrow-right me-2"></i> Log Out </a>
        </nav>
        {% endif %}

        <!-- Dynamic Content from Child Template -->
        <div class="content {% if hide_nav %}login-center{% endif %}">
            {% block content %}
            <!-- Child content will appear here -->
            {% endblock %}
        </div>
    </div>

    <footer class="bg-light text-center text-lg-start py-3 border-top">
        <div class="text-center text-muted">
            &copy; {{ year }} Indotraktor Command Data Center All rights reserved.
        </div>
    </footer>
    <script src="{{ url_for('static', filename='js/collapse.js') }}"></script>
</body>
</html>

templates/IBC.html
<!-- templates/IBC.html -->
{% extends 'Base.html' %}
{% block content %}
    <h2>Interdepartment Business Case (Comming Soon)</h2>
{% endblock %}

templates/Login.html
<!-- templates/Login.html -->
{% extends 'Base.html' %}
{% set hide_nav=True %}
{% block content %}
    <div class="container-login">
        <div class="login-card">
            <div class="login-box">
                <h2> Login User </h2>
                <form method="POST" action="{{ url_for('auth.login')}}">
                    <div class="input-group">
                        <span class="icon">📧</span>
                        <input type="text" placeholder="Input Your User ID/ Email" required />
                    </div>
                    <div class="input-group">
                        <span class="icon">🔑</span>
                        <input type="password" placeholder="Input Your Password" required />
                    </div>
                    <div class="options">
                        <label><input type="checkbox" /> Remember Me </label>
                        <a href="#"> Forget Password </a>
                    </div>
                    <button type="submit" class="btn-login"> Login </button>
                </form>
            </div>
        </div>
        <div class="info-box">
            <h2>Welcome Back!</h2>
            <p class="subtitle">To Indotraktor Interdepartment Business Case</p>
            <span>Don't have an Account?</span>
            <button class="btn-signup">Sign up Here!</button>
        </div>
    </div>
{% endblock %}

templates/Pre_delivery_list.html
<!-- templates/Pre_delivery_list.html -->
{% extends 'Base.html' %}
{% block content %}
    <h2>Pre Delivery List (Comming Soon)</h2>
{% endblock %}

templates/Storage_maintenance_list.html
<!-- templates/Storage_maintenance_list.html -->
{% extends 'Base.html' %}
{% block content %}
    <h2>Storage Maintenance List (Comming Soon)</h2>
{% endblock %}